FROM ghcr.io/scrtlabs/localsecret:beta-nested-attributes

RUN curl https://sh.rustup.rs -sSf |  sh -s -- -y

RUN bash -c "source ${HOME}/.bashrc" 

RUN apt install --assume-yes clang

RUN apt install --assume-yes binaryen

ENV PATH="/root/.cargo/bin:${PATH}"

RUN rustup target add wasm32-unknown-unknown

ENTRYPOINT ["./bootstrap_init.sh"]